name: GStreamer Windows

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ gstreamer/** ]

jobs:
  build:
    runs-on: windows-2016

    steps:

      # Install GStreamer
      - name: Install GStreamer and save to PATH
        shell: powershell
        run: |
          choco install gstreamer;

          # Setup and use the Chocolatey helpers
          Import-Module "${ENV:ChocolateyInstall}\helpers\chocolateyProfile.psm1";
          Update-SessionEnvironment;

          Get-ChildItem env:;
          ${ENV:Path}.Split(';');

          # Save PATH for future steps
          Write-Output "${ENV:PATH}" | Out-File -FilePath "${ENV:GITHUB_PATH}" -Encoding utf8

          # You can also do this manually, but risk that the environment variable name changes
          # This has already changed once during the 1.18.0 release
          # https://github.com/jmcker/ChocolateyPackages/commit/6dff4a1ae842fbbe43942865a2ad421b00b3abd4
          # echo "${ENV:GSTREAMER_1_0_ROOT_MSVC_X86_64}\bin" | Out-File -FilePath "${ENV:GITHUB_PATH}" -Encoding utf8 -Append;

      - name: Check PATH
        shell: powershell
        run: |
          Get-ChildItem env:;
          ${ENV:Path}.Split(';');

          where.exe gst-launch-1.0;
          gst-launch-1.0 --version;
